### ISSUE TITLE
Add duplicate_of support

### ISSUE THREAD

**Issue by mobitar** [standardnotes/snjs#20]
The new syncing server uses a top-level `duplicate_of` field that is equal the to the UUID of the item this item is a duplicate of. Currently production snjs implements this via `item.content.conflict_of`, which is encrypted to the server. In the new behavior, we want to move this value up to the main level (`item.duplicate_of`).

The server uses this to determine how to handle revision history for items that have been conflicted.

cc @karolsojko

**Comment by karolsojko** [comment]
Relates to: https://github.com/standardnotes/syncing-server/pull/60

**Comment by baptiste-grob** [comment]
Let me make sure I understand this correctly:

`item.content.conflict_of` should be used instead of `item.duplicate_of`.

1. What's the compatibility story/what are things I should watch out for?
1. Should snjs handle both fields at the same time, i-e can `item.duplicate_of` be compared with `item.payload.conflict_of`?
1. Should we migrate existing items to this new format, and if so when? Thinking about server load here, but maybe there are other considerations. I'm assuming this migration can only be done on the client since `conflict_of` is part of `item.payload`, which I believe is encrypted (correct me if I'm wrong).

**Comment by mobitar** [comment]
> item.content.conflict_of should be used instead of item.duplicate_of.

Nope, you have it backwards. I've updated the main text to clarify this.

> What's the compatibility story/what are things I should watch out for?

Currently item.content.conflict_of is cleared whenever the item is selected. This way it removes the "Conflicted Copy" flag in the UI. What we'll do is keep item.content.conflict_of as a UI flag. But item.duplicate_of should never be cleared and is permanent. It should be set when an item is duplicated. And should not be used in the UI. It's only a server flag. Anything the UI needs should be in the content.conflict_of field.

> Should snjs handle both fields at the same time, i-e can item.duplicate_of be compared with item.payload.conflict_of?

I think the above should also answer this. We will keep both. One is server-centric, the other is UI centric.

> Should we migrate existing items to this new format, and if so when? Thinking about server load here, but maybe there are other considerations. I'm assuming this migration can only be done on the client since conflict_of is part of item.payload, which I believe is encrypted (correct me if I'm wrong).

We don't need to migrate existing items. This feature is largely related to the new note history feature, and there won't be any history for pre-existing items.
