### ISSUE TITLE
Import creates tag with duplicate name in Windows app

### ISSUE THREAD

**Issue by lnolan5017** [standardnotes/snjs#243]
**Describe the bug**
Importing a note with the same tag name as an existing tag creates a unique tag with the same name in Windows app.

**To Reproduce**
1. Create a tag and attach it to a set of notes.
2. Import notes that have the same tag name. I did this by tagging notes in Evernote, exporting to .enex, then converting to an import file for Standard Notes.
3. A new unique tag with the same name is created.
4. There are now two tags with the same name but with different sets of notes.

**Expected behavior**
If the tag name matches one already in Standard Notes, either attach the imported notes to the existing tag or give an option to merge with the existing tag or create a new tag with a new name.

**Desktop (please complete the following information):**
-  OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by JaspalSuri** [comment]
Hi @lnolan5017,

Sorry for the delayed response. Thank you for taking the time to report this issue to us. We're aware of this issue and providing a fix for this bug is on our todo list.

In the meantime you can use the **Batch Manager** extension to locate and remove several duplicate tags at once. If you need to import a backup again in the future, please sign out first, import the backup, and then sign in. For more detailed instructions, please refer to [this support article](https://docs.standardnotes.org/troubleshooting/import-backups/). 

Please let me know if you have any additional feedback or questions.
