### ISSUE TITLE
Questions about two parts of the code

### ISSUE THREAD

**Issue by standardorcawolf** [standardnotes/snjs#303]
What is a Room SN|Component?

I'm trying to migrate Flame Enigma to a setup where each secret is in a seperate note but is collectively 'the passwords database'.
This provides several key benefits that aren't easily replicatable within a single page note. 

1) Tagging and organizing secrets like you would any other note
2) Easy searching on mobile (even with no extension installed)

However this requires there to be a long running process that is independent of each note's editor so that things such as synchronization can still occur without having to remember to open up the effected notes.

Why does markDone() clear a function after executing it once?

(This is withing the migration system).

**Comment by mobitar** [comment]
The room area describes components residing in the footer of the app. I believe presently this is only the Extensions manager component itself. So if you register your component as a room, a dock shortcut will be created.

markDone() is called after a migration completes so that the migration does not run again after it has completed.
